package eu.wohlben.qits.events.api;

import static io.restassured.RestAssured.given;

import io.quarkus.test.junit.QuarkusTest;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import org.junit.jupiter.api.Test;

/**
 * Writes {@code docs/openapi.yml} as a side effect of the suite, the same way the sibling services
 * do. Checking the document in is what turns an API change into a reviewable diff instead of
 * something a caller discovers at runtime.
 *
 * <p>This is a test only because {@code @QuarkusTest} is the cheapest way to stand the application
 * up and read its own {@code /events/q/openapi} — that path is {@code
 * quarkus.http.non-application-root-path}, not {@code quarkus.rest.path}, so it moves with the
 * former alone.
 *
 * <p>It asserts nothing — the assertion is the diff.
 *
 * <p>The test classpath is indexed too, so any {@code @Path} resource under {@code src/test} lands
 * in the committed document unless it is {@code @Operation(hidden = true)} — which is why {@code
 * IdentityEchoResource} and {@code LogProbeResource} carry it.
 *
 * <p>{@code /events/stream} appears here in no form: a {@code @WebSocket} is not a JAX-RS route, so
 * OpenAPI describes none of it. The document is the HTTP surface, not the whole wire surface.
 *
 * <p>Its SSE twin <b>does</b> appear, and the asymmetry is the point rather than an inconsistency:
 * {@code GET /events/api/stream} is an ordinary JAX-RS route producing {@code text/event-stream},
 * so the document can name the path, the {@code ?names=} parameter and the media type — and cannot
 * say anything about the frames, because OpenAPI has no vocabulary for a stream's elements. A reader
 * of the document learns the door exists and has to read {@code EventStreamResource} for the
 * protocol.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  @Test
  public void exportOpenApiSchema() throws Exception {
    String schema =
        given().when().get("/events/q/openapi").then().statusCode(200).extract().asString();

    // The module is `service/`, so this resolves to the repo root's docs/.
    Path docsDir = Paths.get("../docs");
    if (!Files.exists(docsDir)) {
      Files.createDirectories(docsDir);
    }

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service -am test -Dtest=OpenApiSchemaExportTest"
            + " -Dsurefire.failIfNoSpecifiedTests=false` to regenerate.\n";

    Files.writeString(docsDir.resolve("openapi.yml"), header + schema);
  }
}
